### ISSUE TITLE
C-PERMISSIVE and MPLv2

### ISSUE THREAD

**Issue by RazrFalcon** [rust-lang/api-guidelines#122]
What about MPLv2? Does it not preferable, but acceptable?

**Comment by est31** [comment]
MPLv2 has a weak copyleft. Using a MPL licensed crate as a dependency doesn't influence license considerations of the combined binary, while using a LGPL or GPL licensed crate does. I'd therefore classify it as permissive.

**Comment by BurntSushi** [comment]
`C-PERMISSIVE` is listed under the category "necessities", which states:

> Necessities (to whom they matter, they really matter)

I am definitely among the group of people to whom they matter. Namely, I will not knowingly allow a non-permissively licensed dependency, including MPL, into any of my crates under normal circumstances.

Do you know of any widely recognized organization that qualifies MPL as permissive? If not, I don't think we should be the first.

**Comment by est31** [comment]
IANAL, but for me it seems that unless you want to patch the MPL2 licensed dependency, you will be able to keep your program proprietary and can distribute binaries and so forth. Of course, if you are over-cautious as a business that's your decision.

The term permissive isn't really well defined and has some issues. http://copyfree.org/policy/permissive

It might be the best idea to go with the [copyfree](http://copyfree.org/) proposal. It sees both Apache2.0 and MPL as well as GPL/LGPL as not copyfree. The alternative would be to come up with our own definition that includes MPL. It would be worthwhile IMO but is much more of a hassle. These guidelines can't do more than gently nudging people and if you gently nudge people towards Apache2.0/MIT then that's never wrong.

Beyond the issues raised by the website about Apache2.0 there is the incompatibility with GPL version 2 which is really bad because Apache2.0 is compatible with proprietary software but many free software projects don't have access.

**Comment by BurntSushi** [comment]
I think the current guidelines are fine.

**Comment by Centril** [comment]
My 2 cents:

There should not be pressure in the rust community to pick a permissive license.
I think the text in C-permissive should be worded in such a way that makes it clear that this is not a stance against the GPL or any other copyleft license, but only to inform users that the rust project uses such and such license. So I'd word that section this way: If you want to license permissively, use ASL2.0 + MIT for maximum compatibility.

**Comment by KodrAus** [comment]
I also think the current guidelines are fine. They're specifically talking about compatible licensing for libraries that aligns with the options chosen by the project itself.

**Comment by KodrAus** [comment]
@rfcbot fcp close

**Comment by KodrAus** [comment]
@rfcbot fcp close

This suggests leaving our guideline about permissive licensing as-is, with its recommendation of dual Apache/MIT for equivalence with the Rust project itself and maximum compatibility in the ecosystem.

**Comment by BurntSushi** [comment]
I ticked my box. Just in case rfcbot unticks it.
