### ISSUE TITLE
Preludes?

### ISSUE THREAD

**Issue by killercup** [rust-lang/api-guidelines#140]
In general, it seems that the usage of glob imports (`use foo::*;`) is generally discouraged in Rust [[1]], while at the same time the std lib and some other crates offer "prelude" modules [[2]] that users are supposed to glob import for convenience.

Should there be a guideline describing when/whether a prelude is good to have?

[1]: https://doc.rust-lang.org/book/first-edition/crates-and-modules.html
[2]: https://github.com/search?utf8=✓&q=mod+prelude+language%3ARust&type=Code

- - -

Sorry if this is not something that is considered "API" enough for the API guidelines.

Context: https://github.com/killercup/assert_cli/pull/75#issuecomment-340608533 made me look up what the API guidelines say, and I couldn't find anything on the topic.

**Comment by emk** [comment]
There are definitely some APIs—especially for things like testing libraries or `diesel`—where I'm going to have to import the same 6 symbols every time I use the library. Usually this is a mix of traits and a few essential functions or types.

Personally, I'm rather fond of glob imports for cases like these, because otherwise I have to spend a lot more time digging around in the docs and figuring out errors just to get things done. Yes, I understand that in some sense it's not "ideal", because a new export might someday be added to the glob and conflict with some other import. But that's absolutely a risk I'm willing to pay in the name of convenience for certain carefully-chosen APIs.

I _do_ have a rule of "no glob imports for things which _aren't_ preludes", though. That seems pretty sensible.
