### ISSUE TITLE
traits in types are marked with dyn/impl, not bare

### ISSUE THREAD

**Issue by lucasem** [rust-lang/api-guidelines#190]
In Rust 2018, we can mark all trait objects using the `dyn` keyword. Makes it obvious whether `&Foo` is a trait object (`&dyn Foo`) or just a struct reference (`&Foo`) if the user doesn't have context around what `Foo` is.

Any `Trait` present in a type is prefixed with either `dyn` or `impl`. I think this should be a guideline. Easy to enforce via `#![deny(bare_trait_objects)]`, and upheld by rust source (e.g. see the docs/src of [`std::error::Error`](https://doc.rust-lang.org/stable/std/error/trait.Error.html#method.source).

**Comment by dtolnay** [comment]
Thanks!

I think this is out of scope for the API guidelines because the public API of the crate will be the same either way -- and rustdoc will display `dyn` even if you have not written one.

I think this would be more appropriate as a Clippy lint, equivalent to `warn(bare_trait_objects)` but for better visibility among Clippy users.

**Comment by dwijnand** [comment]
> I think this is out of scope for the API guidelines because the public API of the crate will be the same either way -- and rustdoc will display `dyn` even if you have not written one.

That kind of raises the question of whether APIs are consumed from rustdocs or from source.

Also, maybe rather than duplicating lints, Clippy (or rustc) should somehow highlight or link to lints already in rustc?  This will become even more relevant as clippy lints are uplifted into rustc.

Finally, by virtue of being a rustc lint, you can update your sources to use the `dyn` keyword with `cargo fix --edition-idioms`, though note that (AFAIK) that option is still a bit buggy (which is why it isn't that known).
