### ISSUE TITLE
Naming convention for crates

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/api-guidelines#29]
The current guideline says "`snake_case` (but prefer single word)." Is this still the case? Why do new high-profile crates like `tokio-core` use kebab case?

**Comment by dtolnay** [comment]
I still think it shouldn't matter. https://github.com/rust-lang/cargo/issues/2775

**Comment by chris-morgan** [comment]
Two things are being conflated here: *crates* and *packages*.

A *crate* is the unit of compilation and that which you import into your code; its name must be a Rust identifier, and is conventionally unspecified, allowing it to determined automatically (from the package name with `-` changed to `_`, for library crates).

A *package* is the directory containing Cargo.toml, which could include a lib crate, multiple bin crates, examples, tests, *&c.*. It is *their* naming convention that is unclear—though there are certain strong subconventions like *-sys. (The history of hyphens versus underscores is not particularly well documented; yet I say that kebab-case was the preferred convention the last time this was discussed; snake_case has gained in popularity because no declaration was made at that time of one particular form as preferred.)

**Comment by cheako** [comment]
This is confusing, I'm looking to run cargo new on a polar perlin noise loop...  Well actually polar OpenSimplex noise loop.  The loop is optional as I can't find "polar perlin noise .*" that's not loop.

What should I type, should I just make up some silly name or acronym so it's one word?

**Comment by chris-morgan** [comment]
@cheako That’s not the type of naming convention that’s being spoken about here. You could call it polar-opensimplex-noise-loop if you wanted to if that’s not taken, or some other silly name, or whatever you like. What’s being talked about here is matters like whether you should use `_` or `-`; that you should shun `-rs` suffixes and `rust-` prefixes; the convention of `-sys` suffixes; and any other conventions like `foo` being accompanied by `foo-macros` and `foo-shared` crates where necessary.

**Comment by dlee13** [comment]
I'm still confused. Should my new rust project use snake_case or kebab-case?

**Comment by BurntSushi** [comment]
Personally, I have always, and continue to use, kebab case for crate names.

**Comment by dumindu** [comment]
With reference the discussion had in [r/rust/](https://www.reddit.com/r/rust/comments/g43kf5/the_naming_convention_for_crates_and_file_names/),

Even though `snake_case` is the initial convention on crates and file names, even the official docs uses `kebab-case` on crate names and in some examples, both `snake_case` and `kebab-case` have been mixed while naming files. 

https://rust-lang.github.io/api-guidelines/naming.html
> In general, Rust tends to use UpperCamelCase for "type-level" constructs (types and traits) and snake_case for "value-level" constructs. More precisely:

To reduce confusions and to make docs and code more consistent, I think better promote `snake_case` instead `kebab-case`, at least on official docs.

**Comment by daira** [comment]
Given that `-`s in the package name are going to be changed to `_`s anyway in the code by default, why would you use anything other than snake_case for package names? It's not as though `-` has any semantic significance; it's just a pointless source of variation.

**Comment by camsteffen** [comment]
A naming convention has already been accepted in RFC 430. The fact that it has not been followed is an issue. But, in my opinion, [removing](https://github.com/rust-lang/api-guidelines/commit/5e4b27a54e67ee8acc266cb3c98119a801c6ca77) the convention altogether is not merited.
